version: "3.9"

services:
  db:
    image: postgres:14-alpine
    volumes:
      - ../db:/var/lib/postgresql/data

    environment:
      - POSTGRES_DB=actix
      - POSTGRES_USER=actix
      - POSTGRES_PASSWORD=actix
    ports:
      - "5432:5432"
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"